version: '3'
services:
  mysql-master:
    image: mysql:5.7.16 
    restart: always
    container_name: mysql-master
    hostname: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: admin@1024
      TZ: Asia/Shanghai
    networks:
      - mysql-group-net
    ports:
      - 3306:3306
    volumes:
      - ./mysql-master/data:/var/lib/mysql
      - ./mysql-master/conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$${MYSQL_ROOT_PASSWORD} -e 'select 1;' >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  mysql-slave:
    image: mysql:5.7.16 
    restart: always
    container_name: mysql-slave-01
    hostname: mysql-slave-01
    environment:
      MYSQL_ROOT_PASSWORD: admin@1024
      TZ: Asia/Shanghai
    networks:
      - mysql-group-net
    ports:
      - 3307:3306
    volumes:
      - ./mysql-slave-01/data:/var/lib/mysql
      - ./mysql-slave-01/conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$${MYSQL_ROOT_PASSWORD} -e 'select 1;' >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

     
networks:
  mysql-group-net:
    driver: bridge


